TMP: original commit (modified with rebase)

diff --git a/.github/actions/build-docker/action.yml b/.github/actions/build-docker/action.yml
--- a/.github/actions/build-docker/action.yml
+++ b/.github/actions/build-docker/action.yml
@@ -1,114 +1,186 @@
-name: 'Docker Build'
-description: 'Builds `addons-server` docker image'
+name: 'Build Docker Image'
+description: 'Build docker image and optinally push to registry'
 inputs:
-  password:
-    required: false
-    description: "Docker registry password"
-    default: "invalid"
-  push:
-    required: false
-    description: "Build and push image to registry (cannot be used together with load)"
-    default: "false"
-  username:
-    required: false
-    description: "Docker registry username"
-    default: "invalid"
+    # Required Inputs
+    registry:
+      required: true
+      description: docker registry to publish to
+    image:
+      required: true
+      description: docker image to tag the image
+    version:
+      required: true
+      description: docker image version to tag the image
+    target:
+      required: true
+      description: docker image target to build to
+    # Optional Inputs
+    artifact_name:
+      required: false
+      description: optionally define the full artifact name
+      default: ''
+    username:
+      required: false
+      description: the username to login with
+      default: ''
+    password:
+      required: false
+      description: the password to login with
+      default: ''
+    push:
+      required: false
+      description: should the image be pushed to the defined registry
+      default: 'false'
+    cache_to:
+      required: false
+      description: Cache the docker image layers to a remote store
+    cache_from:
+      required: false
+      description: Cache to pull before building the image
 
 outputs:
+  artifact_name:
+    description: the artifact where the image was uploaded toJson
+    value: ${{ steps.input_meta.outputs.artifact_name }}
   digest:
-    description: "The Docker image digest"
-    value: ${{ steps.digest.outputs.digest }}
-  version:
-    description: "The Docker version for the image"
-    value: ${{ steps.meta.outputs.version }}
-  tags:
-    description: "The Docker tags for the image"
-    value: ${{ steps.meta.outputs.tags }}
+    description: The image digest from the index.json
+    value: ${{ steps.build.outputs.digest }}
 
 runs:
-  using: "composite"
+  using: 'composite'
   steps:
-    # Setup docker to build for multiple architectures
+    - id: input_meta
+      shell: bash
+      run: |
+        artifact_name="${{ inputs.artifact_name }}"
+        registry="${{ inputs.registry }}"
+        image="${{ inputs.image }}"
+        version="${{ inputs.version }}"
+        target="${{ inputs.target }}"
+        username="${{ inputs.username }}"
+        password="${{ inputs.password }}"
+        push="${{ inputs.push }}"
+        cache_to="${{ inputs.cache_to }}"
+        cache_from="${{ inputs.cache_from }}"
+
+        echo "registry=$registry" >> $GITHUB_OUTPUT
+        echo "image=$image" >> $GITHUB_OUTPUT
+        echo "image_file=image.tar" >> $GITHUB_OUTPUT
+        echo "version=$version" >> $GITHUB_OUTPUT
+        echo "target=$target" >> $GITHUB_OUTPUT
+        echo "cache_to=$cache_to" >> $GITHUB_OUTPUT
+        echo "cache_from=$cache_from" >> $GITHUB_OUTPUT
+
+        if [[ "$target" != 'development' && "$target" != 'production' ]]; then
+          echo "invalid target $target. Expected `production` or `development`"
+          exit 1
+        else
+          echo "target=$target" >> $GITHUB_OUTPUT
+        fi
+
+        base_image="$registry/$image"
+        echo "base_image=$base_image" >> $GITHUB_OUTPUT
+
+        if [[ "$push" == 'true' ]]; then
+          if [[ "$username" != '' && "$password" != '' ]]; then
+            should_push=true
+          else
+            echo "`push` set to true but missing username: $username and/or password: $password"
+            exit 1
+          fi
+        else
+          should_push=false
+        fi
+        echo "should_push=$should_push" >> $GITHUB_OUTPUT
+
+        # Set default artifact name if empty
+        if [[ "$artifact_name" == '' ]]; then
+          artifact_name="build-docker-$target"
+        fi
+        echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT
+
+        cat $GITHUB_OUTPUT
+
+    - name: Login
+      if: ${{ steps.input_meta.outputs.should_push == 'true' }}
+      uses: docker/login-action@v3
+      with:
+        registry: ${{ steps.input_meta.outputs.registry }}
+        # Read username and password directly from inputs as they are likely secrets
+        # and cannot be passed around between step outputs
+        username: ${{ inputs.username }}
+        password: ${{ inputs.password }}
+
+    - name: Docker meta
+      id: docker_meta
+      env:
+        version: ${{ steps.input_meta.outputs.version }}
+        suffix: -next
+      uses: docker/metadata-action@v5
+      with:
+        images: ${{ steps.input_meta.outputs.base_image }}
+        tags: |
+            type=raw,value=${{ env.version }},suffix=${{ env.suffix }}
+
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
+
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
       with:
         version: latest
         buildkitd-flags: --debug
 
-    # Login to a registry to push the image
-    - name: Login to Container Registry
-      # Only login if we are pushing the image
-      if: ${{ inputs.push == 'true' }}
-      uses: docker/login-action@v3
-      with:
-        username: ${{ inputs.username }}
-        password: ${{ inputs.password }}
-
-
-    - name: Suffix for local builds
-      id: suffix
-      shell: bash
-      # The suffix is unique to a branch and commit
-      run: |
-        if [[ "${{ inputs.push }}" == "false" ]]; then
-          echo "suffix=${{ github.ref }}-${{ github.sha }}" >> $GITHUB_OUTPUT
-        else
-          echo "suffix=ci" >> $GITHUB_OUTPUT
-        fi
-
-    # Determine the tags for the image
-    # We need to support custom explicit tags allowing CI to build unique images
-    # that won't be pushed to the registry.
-    - name: Docker meta
-      id: meta
-      uses: docker/metadata-action@v5
-      with:
-        # Hard coding our dockerhub image name
-        images: mozilla/addons-server
-        flavor: |
-          suffix=-${{ steps.suffix.outputs.suffix }}
-        tags: |
-          type=schedule
-          type=ref,event=tag
-          type=ref,event=branch
-          type=ref,event=pr
-          # set latest tag for default branch
-          # Disabled for now as we do not use this action for
-          # The production build
-          # type=raw,value=latest,enable={{is_default_branch}}
-
-    - name: Create .env and version.json files
+    - name: Local Environment Setup
       shell: bash
       env:
-        DOCKER_VERSION: ${{ steps.meta.outputs.version }}
+        DOCKER_REGISTRY: ${{ steps.input_meta.outputs.registry }}
+        DOCKER_IMAGE: ${{ steps.input_meta.outputs.image }}
+        DOCKER_VERSION: ${{ steps.docker_meta.outputs.version }}
         DOCKER_COMMIT: ${{ github.sha }}
         VERSION_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-      run: make setup
-
-    - name: Set Docker Variables
-      id: cache
-      shell: bash
       run: |
-        echo "tag=mozilla/addons-server:${{ steps.meta.outputs.version }}-cache" >> $GITHUB_OUTPUT
+        make setup
 
-    - name: Build Image
+    - name: Build Docker Image
       id: build
-      uses: docker/bake-action@v4
+      uses: docker/build-push-action@v6
       with:
-        targets: web
-        push: ${{ inputs.push }}
-        load: ${{ inputs.push == 'false' }}
-        set: |
-          *.cache-from=type=registry,ref=${{ steps.cache.outputs.tag }}
-          *.cache-to=type=registry,ref=${{ steps.cache.outputs.tag }},mode=max,compression-level=9,force-compression=true,ignore-error=true
+        # Build Context
+        context: .
+        file: Dockerfile
+        target: ${{ steps.input_meta.outputs.target }}
+        platforms: linux/amd64
 
-    - name: Get image digest
-      id: digest
-      shell: bash
-      env:
-        BUILDX_BAKE_METADATA_FILE: metadata.json
-      run: |
-        echo '${{ steps.build.outputs.metadata }}' > metadata.json
-        echo "digest=$(cat metadata.json | jq -r '.web."containerimage.digest"')" >> $GITHUB_OUTPUT
+        # Export the image to `image.tar`
+        # Optionally push to the registry defined in the tag/login
+        load: false
+        outputs: |
+          type=docker,dest=${{ steps.input_meta.outputs.image_file }}
+          type=image,push=${{ steps.input_meta.outputs.should_push }}
+
+        # Metadata
+        tags: ${{ steps.docker_meta.outputs.tags }}
+        annotations: ${{ steps.docker_meta.outputs.annotations }}
+        labels: ${{ steps.docker_meta.outputs.labels }}
+
+        # Cache Information
+        cache-from: ${{ steps.input_meta.outputs.cache_from }}
+        cache-to: ${{ steps.input_meta.outputs.cache_to }}
+
+    - name: Upload Image Artifact
+      uses: actions/upload-artifact@v4
+      with:
+        # We need to upload to a named artifact that is exposed to `run-docker`
+        name: ${{ steps.input_meta.outputs.artifact_name }}
+        # Upload just the single tar file
+        path: ${{ steps.input_meta.outputs.image_file }}
+        # We expect artifacts to be found, explicitly error if none are
+        if-no-files-found: error
+        # Artifacts should not last long, each run will create a new one
+        retention-days: 1
+        # Optimize for speed rather than size
+        compression-level: 1
+        # We should never create the exact same artifact twice in the same run
+        overwrite: false
+
