Merge jobs that run on push to single push workflow

diff --git a/.github/actions/build-docker/action.yml b/.github/actions/build-docker/action.yml
--- a/.github/actions/build-docker/action.yml
+++ b/.github/actions/build-docker/action.yml
@@ -8,7 +8,6 @@ inputs:
   push:
     required: false
     description: "Build and push image to registry (cannot be used together with load)"
-    default: "false"
   username:
     required: false
     description: "Docker registry username"
@@ -29,12 +28,20 @@ runs:
   using: "composite"
   steps:
     - name: Validate inputs
+      id: inputs
       shell: bash
       run: |
-        if [[ "${{ inputs.push  }}" == "true" && "${{ github.ref }}" == "refs/heads/master" ]]; then
-          echo "Cannot push to registry from master branch unless we migrate our master build job to GHA."
-          exit 1
+        if [[ "${{ inputs.push  }}" == "true" ]]; then
+          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
+            echo "Cannot push to registry from master branch unless we migrate our master build job to GHA."
+            exit 1
+          fi
+
+          echo "push=true" >> $GITHUB_OUTPUT
+        else
+          echo "push=false" >> $GITHUB_OUTPUT
         fi
+
     # Setup docker to build for multiple architectures
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
@@ -47,7 +54,7 @@ runs:
     # Login to a registry to push the image
     - name: Login to Container Registry
       # Only login if we are pushing the image
-      if: ${{ inputs.push == 'true' }}
+      if: ${{ steps.inputs.outputs.push }}
       uses: docker/login-action@v3
       with:
         username: ${{ inputs.username }}
@@ -59,10 +66,10 @@ runs:
       shell: bash
       # The suffix is unique to a branch and commit
       run: |
-        if [[ "${{ inputs.push }}" == "false" ]]; then
-          echo "suffix=${{ github.ref }}-${{ github.sha }}" >> $GITHUB_OUTPUT
-        else
+        if [[ "${{ steps.inputs.outputs.push }}" == "true" ]]; then
           echo "suffix=ci" >> $GITHUB_OUTPUT
+        else
+          echo "suffix=${{ github.ref }}-${{ github.sha }}" >> $GITHUB_OUTPUT
         fi
 
     # Determine the tags for the image
@@ -99,8 +106,8 @@ runs:
       uses: docker/bake-action@v4
       with:
         targets: web
-        push: ${{ inputs.push }}
-        load: ${{ inputs.push == 'false' }}
+        push: ${{ steps.inputs.outputs.push }}
+        load: ${{ !steps.inputs.outputs.push }}
 
     - name: Get image digest
       id: digest
