Generate version.json as part of docker build: - remove git dependency from version.json generation - use only version.json file for sentry release with soft/hard fail
Compile locales independently of prod.txt pip install
- install compile-mo.sh deps independently
- properly named stage
- allows locale compilation to occur in parallel of pip install prod.txt

Set docker image/version based on environment:
- set DOCKER_IMAGE:DOCKER_VERSION vars in make file
- use dynamic values for image in docker-compose.yml
- set tag in circleCI/action using vars
- remove rudundant retagging

Use buildx bake for docker image building across all environments

TMP: DOCKER_TARGET from env

Use docker compose to run CI actions

TMP: remove olympia mount from ci.yml

TMP: olympia mount compose_files

TMP: remove localization

Use multi stage build to enable development/production container

TMP: instal olympia more efficiently

diff --git a/.github/actions/build-docker/action.yml b/.github/actions/build-docker/action.yml
--- a/.github/actions/build-docker/action.yml
+++ b/.github/actions/build-docker/action.yml
@@ -17,22 +17,38 @@ inputs:
     required: false
     description: "Docker registry username"
     default: "invalid"
+  target:
+    required: false
+    description: "Build target"
+    default: "development"
 
 outputs:
   tags:
     description: "The Docker tags for the image"
     value: ${{ steps.meta.outputs.tags }}
+  version:
+    description: "The Docker version for the image"
+    value: ${{ steps.meta.outputs.version }}
 
 runs:
   using: "composite"
   steps:
     - name: Validate inputs
       shell: bash
+      id: valid_inputs
       run: |
         if [[ "${{ inputs.push  }}" == "true" && "${{ github.ref }}" == "refs/heads/master" ]]; then
           echo "Cannot push to registry from master branch unless we migrate our master build job to GHA."
           exit 1
         fi
+
+        if [[ "${{ inputs.target }}" != "development" && "${{ inputs.target }}" != "production" ]]; then
+          echo "Invalid target: ${{ inputs.target }}"
+          exit 1
+        fi
+
+        echo "image=mozilla/addons-server" >> $GITHUB_OUTPUT
+
     # Setup docker to build for multiple architectures
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
@@ -56,8 +72,7 @@ runs:
       id: meta
       uses: docker/metadata-action@v5
       with:
-        # Hard coding our dockerhub imnage name
-        images: mozilla/addons-server
+        images: ${{ steps.valid_inputs.outputs.image }}
         tags: |
           type=schedule
           type=ref,event=tag
@@ -68,16 +83,34 @@ runs:
           # The production build
           # type=raw,value=latest,enable={{is_default_branch}}
 
+    - name: Export environment for docker compose
+      shell: bash
+      run: |
+        # Set image name and tag for docker-compose.yml file
+        make create_env_file \
+          DOCKER_IMAGE=${{ steps.valid_inputs.outputs.image }} \
+          DOCKER_VERSION=${{ steps.meta.outputs.version }} \
+          DOCKER_COMMIT=${{ github.sha }}
+
+    - name: Create version
+      shell: bash
+      # Currently producing a version "refs/head/master" or "refs/tag/2024.10.10"
+      run: make version
+
     - name: Build Image
-      uses: docker/build-push-action@v5
+      id: build
+      uses: docker/bake-action@v4
       with:
-        context: .
-        platforms: linux/amd64
+        targets: web
+        files: |
+          docker-compose.yml
+          ${{ steps.meta.outputs.bake-file-tags }}
+          ${{ steps.meta.outputs.bake-file-annotations }}
+          ${{ steps.meta.outputs.bake-file-labels }}
         pull: true
         push: ${{ inputs.push }}
         load: ${{ inputs.push == 'false' }}
-        tags: ${{ steps.meta.outputs.tags }}
-        cache-from: type=gha
-        cache-to: type=gha,mode=max
-        build-args: |
-            PYTHON_VERSION=${{ inputs.python_version }}
+        set: |
+          *.target=${{ inputs.target }}
+          *.cache-from=type=gha
+          *.cache-to=type=gha,mode=max
diff --git a/.github/workflows/verify-docker-image.yml b/.github/workflows/verify-docker-image.yml
--- a/.github/workflows/verify-docker-image.yml
+++ b/.github/workflows/verify-docker-image.yml
@@ -12,17 +12,109 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Build Docker image
-        id: build
+      - id: build
         uses: ./.github/actions/build-docker
+        with:
+          target: development
 
-      - name: Smoke test
+      - name: Create failure
+        id: failure
         uses: ./.github/actions/run-docker
         with:
-          image: ${{ steps.build.outputs.tags }}
-          options:
-          run: |
-            make update_deps
+          image: ${{ steps.build.outputs.image }}
+          version: ${{ steps.build.outputs.version }}
+          command: |
+            exit 1
+        continue-on-error: true
+      - name: Verify failure
+        if: always()
+        run: |
+          if [ "${{ steps.failure.outcome }}" -ne "failure" ]; then
+            echo "Expected failure"
+            exit 1
+          fi
+
+      - name: Check (special characters in command)
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ steps.build.outputs.version }}
+          command: |
+            echo 'this is a question?'
+            echo 'a * is born'
+            echo 'wow an array []'
+
+      - name: Manage py check
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ steps.build.outputs.version }}
+          command: |
             echo 'from olympia.lib.settings_base import *' > settings_local.py
             DJANGO_SETTINGS_MODULE='settings_local' python3 ./manage.py check
 
+      - name: Installed packages
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ steps.build.outputs.version }}
+          command: |
+            pip show olympia
+
+  test:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - id: build
+        uses: ./.github/actions/build-docker
+        with:
+          target: development
+
+      - name: Run Test
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ steps.build.outputs.version }}
+          up: ''
+          command: |
+            pytest \
+              -n auto \
+              -m 'not es_tests and not needs_locales_compilation and not static_assets and not internal_routes_allowed' \
+              -v src/olympia/amo
+
+  locales:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
+
+      - name: Build Docker image
+        id: build
+        uses: ./.github/actions/build-docker
+        with:
+          target: development
+
+      - name: Extract Locales
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ steps.build.outputs.version }}
+          compose_file: docker-compose.olympia.yml
+          command: |
+            make extract_locales
+
+      - name: Push Locales (dry-run)
+        shell: bash
+        run: |
+          if [[ ${{ github.event.pull_request.head.repo.fork}} == 'true' ]]; then
+            echo """
+            Github actions are not authorized to push from workflows triggered by forks.
+            We cannot verify if the l10n extraction push will work or not.
+            Please submit a PR from the base repository if you are modifying l10n extraction scripts.
+            """
+
+            exit 0
+          fi
+
+          make push_locales ARGS="--dry-run"
