Load service data via portable and persistent data volumes
Load storage via persistent data volume (host bound)

Make up/down commands to easily recreate local environments

diff --git a/Makefile-os b/Makefile-os
--- a/Makefile-os
+++ b/Makefile-os
@@ -7,6 +7,11 @@ DOCKER_PUSH ?= false
 DOCKER_OUTPUT ?=
 DOCKER_COMMIT ?= $(shell git rev-parse HEAD || echo "commit")
 VERSION_BUILD_URL ?= build
+
+BACKUPS_DIR = $(shell pwd)/backups
+EXPORT_DIR = $(BACKUPS_DIR)/$(shell date +%Y%m%d%H%M%S)
+RESTORE_DIR ?= $(BACKUPS_DIR)/$(shell ls -1 backups | sort -r | head -n 1)
+
 # Exporting these variables make them default values for docker-compose*.yml files
 export DOCKER_VERSION ?= local
 
@@ -30,11 +35,7 @@ push_locales: ## extracts and merges translation strings
 	bash ./scripts/push_l10n_extraction.sh $(ARGS)
 
 .PHONY: update_docker
-update_docker: ## update all the docker images
-	docker compose exec --user olympia worker make update_deps
-	docker compose exec --user olympia web make update
-	docker compose restart web
-	docker compose restart worker
+update_docker: data_export up data_restore ## update all the docker images
 
 .PHONY: shell
 shell: ## connect to a running addons-server docker shell
@@ -50,6 +51,26 @@ create_env_file:
 	echo "HOST_UID=${HOST_UID}" >> .env
 	echo "SUPERUSER_EMAIL=${SUPERUSER_EMAIL}" >> .env
 	echo "SUPERUSER_USERNAME=${SUPERUSER_USERNAME}" >> .env
+
+SERVICES_PATHS := \
+    "elasticsearch:/usr/share/elasticsearch/data" \
+    "rabbitmq:/var/lib/rabbitmq"
+
+.PHONY: data_export
+data_export:
+	@ mkdir -p $(EXPORT_DIR)
+
+	# Extracting mysql database
+	docker compose exec mysqld /usr/bin/mysqldump olympia > $(EXPORT_DIR)/data_mysqld.sql
+
+.PHONY: data_restore
+data_restore:
+	@[ -d $(RESTORE_DIR) ] || (echo "Directory $(RESTORE_DIR) does not exist" && exit 1)
+
+	# Restoring mysql database
+	docker compose exec -T mysqld /usr/bin/mysql olympia < $(RESTORE_DIR)/data_mysqld.sql
+
+	$(MAKE) reindex_data
 
 .PHONY: create_docker_builder
 create_docker_builder: ## Create a custom builder for buildkit to efficiently build local images
@@ -84,18 +105,25 @@ docker_compose_config: ## Show the docker compose configuration
 	echo $(DOCKER_BUILD_ARGS)
 
 .PHONY: build_docker_image
-build_docker_image: create_docker_builder version docker_compose_config ## Build the docker image
-	docker buildx bake web $(DOCKER_BUILD_ARGS) --print
+build_docker_image: create_docker_builder version ## Build the docker image
 	docker buildx bake web $(DOCKER_BUILD_ARGS)
 
+.PHONY: docker_compose_down
+docker_compose_down: ## Stop the docker containers
+	docker compose down --rmi local --remove-orphans
+
 .PHONY: clean_docker
-clean_docker: ## Clean up docker containers, images, caches, volumes and local cache directories. Use with caution. To restart the app run make initialize_docker after this commandUse with caution.
-	docker compose down --rmi local --volumes --remove-orphans
+clean_docker: docker_compose_down ## Clean up docker containers, images, caches, volumes and local cache directories. Use with caution. To restart the app run make initialize_docker after this command.
+	docker compose down --volumes
 	docker buildx prune -af
 	rm -rf ./deps/**
 
-.PHONY: initialize_docker
-initialize_docker: create_env_file build_docker_image
+.PHONY: docker_compose_up
+docker_compose_up: ## Start the docker containers
+	docker compose up $(DOCKER_SERVICES) -d --wait --remove-orphans --force-recreate --quiet-pull $(ARGS)
+
+.PHONY: docker_extract_deps
+docker_extract_deps: ## Extract dependencies from the docker image to a local volume mount
 # Run a fresh container from the base image to install deps. Since /deps is
 # shared via a volume in docker-compose.yml, this installs deps for both web
 # and worker containers, and does so without requiring the containers to be up.
@@ -108,7 +136,15 @@ initialize_docker: create_env_file build_docker_image
 	# mounting ./deps:/deps effectively removes dependencies from the /deps directory in the container
 	# running `update_deps` will install the dependencies in the /deps directory before running
 	docker compose run --rm web make update_deps
-	docker compose up -d
+
+.PHONY: up
+up: create_env_file version docker_extract_deps docker_compose_up ## Create and start docker compose
+
+.PHONY: down
+down: docker_compose_down ## Stop the docker containers
+
+.PHONY: initialize_docker
+initialize_docker: up
 	docker compose exec --user olympia web make initialize
 
 %: ## This directs any other recipe (command) to the web container's make.
