Add validation for DOCKER_* variables: - add explicit make build command - Refactored setup.py to improve metadata handling for Docker images, including validation of environment variables.

diff --git a/.github/workflows/_test_check.yml b/.github/workflows/_test_check.yml
--- a/.github/workflows/_test_check.yml
+++ b/.github/workflows/_test_check.yml
@@ -61,16 +61,28 @@ jobs:
           - production
     steps:
       - uses: actions/checkout@v4
-      - shell: bash
-        continue-on-error: true
+
+      - name: Context
+        id: context
+        shell: bash
         run: |
-          cat <<EOF
-            Values passed to the action:
-            version: ${{ matrix.version }}
-            target: ${{ matrix.target }}
-            deps: ${{ matrix.deps }}
-          EOF
+          version="${{ matrix.version }}"
+          target="${{ matrix.target }}"
+
+          expect_failure=false
+
+          # For non local images, running in "development" mode is invalid and will fail
+          # during setup. This state allows us to confirm the failure happens as expected.
+          if [[ "$version" != "local" && "$target" == "development" ]]; then
+            expect_failure=true
+          fi
+
+          echo "expect_failure=$expect_failure" >> "$GITHUB_OUTPUT"
+          cat "$GITHUB_OUTPUT"
+
       - name: ${{ matrix.version == 'local' && 'Uncached Build' || 'Pull' }} Check
+        id: build
+        continue-on-error: true
         uses: ./.github/actions/run-docker
         # Set environment variables that are expected to be ignored
         env:
@@ -81,9 +93,21 @@ jobs:
           target: ${{ matrix.target }}
           deps: ${{ matrix.deps }}
           run: make check
+
+      - name: Verify build
+        id: verify
+        shell: bash
+        run: |
+          expect_failure="${{ steps.context.outputs.expect_failure }}"
+          build_outcome="${{ steps.build.outcome }}"
+          if [[ "$expect_failure" == "false" && "$build_outcome" == "failure" ]]; then
+            echo "Expected failure"
+            exit 1
+          fi
+
       - name: Cached Build Check
         uses: ./.github/actions/run-docker
-        if: ${{ matrix.version == 'local' }}
+        if: matrix.version == 'local' && steps.verify.outcome == 'success'
         with:
           version: ${{ matrix.version }}
           target: ${{ matrix.target }}
