TMP: use build workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,8 +50,18 @@ jobs:
         id: context
         uses: ./.github/actions/context
 
+  build_workflow:
+    permissions:
+      contents: read
+      id-token: write
+    uses: ./.github/workflows/_build.yml
+    with:
+      artifact_name: build-docker-next-development
+    secrets: inherit
+
   build:
     runs-on: ubuntu-latest
+    needs: context
     outputs:
       artifact_name: ${{ steps.build.outputs.artifact_name }}
       tag: ${{ steps.build.outputs.tag }}
@@ -68,6 +78,9 @@ jobs:
           target: ${{ inputs.target || 'development' }}
           cache_to: ${{ inputs.cache_to || 'type=gha,mode=max' }}
           cache_from: ${{ inputs.cache_from || 'type=gha' }}
+          push: ${{ needs.context.outputs.is_fork != 'true' }}
+          username: ${{ secrets.DOCKER_USER }}
+          password: ${{ secrets.DOCKER_PASS }}
 
   test_make_docker_configuration:
     runs-on: ubuntu-latest
@@ -102,12 +115,10 @@ jobs:
             exit 1
 
       - name: Verify failure
-        if: always()
+        if: steps.failure.outcome == 'success'
         run: |
-          if [[ "${{ steps.failure.outcome }}" != "failure" ]]; then
-            echo "Expected failure"
-            exit 1
-          fi
+          echo "Expected failure"
+          exit 1
 
       - name: Check (special characters in command)
         uses: ./.github/actions/run-docker
