Enhance health check workflows and scripts (#23190)
* Enhance health check workflows and scripts

- Added output for fork detection in health_check_completed.yml.
- Updated health_check.yml to ensure health check file existence before proceeding.
- Refactored health_check.py to use a session with retries for HTTP requests, improving error handling.
- Modified tests in test_health_check.py to validate new error handling and retry logic.

* Add dummy waffle switch to test healthcheck e2e in any environment

* CI Completed should use [ci] env for all notifications

diff --git a/.github/workflows/health_check.yml b/.github/workflows/health_check.yml
--- a/.github/workflows/health_check.yml
+++ b/.github/workflows/health_check.yml
@@ -32,6 +32,13 @@ jobs:
           target: development
           version: local
           run: |
+            # On local, we want to ensure there are failures to test
+            # the later steps with so set the waffle switch to on.
+            if [ "${{ matrix.environment }}" = "local" ]; then
+              echo "Set waffle switch dummy-monitor-fails to true"
+              ./manage.py waffle_switch dummy-monitor-fails on
+            fi
+
             ./scripts/health_check.py \
             --env ${{ matrix.environment }} \
             --verbose \
@@ -42,6 +49,11 @@ jobs:
         if: steps.health_check.outcome == 'failure'
         shell: bash
         run: |
+          if [ ! -f ${{ env.health_check_file }} ]; then
+            echo "Health check file is missing from previous step"
+            exit 1
+          fi
+
           # Create the message blocks file
           ./scripts/health_check_blocks.py \
           --input ${{ env.health_check_file }} \
