Run CI in github actions: - modify the actions to be compatible with our requirements - implement each job we have currently in circleCI as a job in the verify image workflow. - currently running make update_deps when we need dev dependencies. This could be achieved with a development stage of our docker build.
TMP: fix

TMP: Fix nginx network invalid

TMP: fix olympia user to allow running in container.

TMP: fix run as root to fix olympia user.

TMP: add shell to olympia user when executing

TMP: Fix missing olympia package.

TMP: skip manage check

TMP: build with tag IMPORTANT otherwise we push latest.

TMP: no olympia on latest?

tmp: try with docker run also

TMP: clean build version

TMP: revert

TMP: PURE PURE PURE

TMP: add the env vars

TMP: use compose command also

TMP: does removing the deps mount work?

TMP: remove build, not needed

TMP: does removing the local mount fix it?

TMP: revert

TMP: move volumes to override

TMP: proof, mounting the deps volume breaks in docker and removing volume fixes in compose.

Use single exec

TMP: fix eof

TMP: use different delimeters for heredoc netsting

TMP: add check reqs script

TMP: check ownership

TMP: test build

TMP: export environment variables needed

TMP: use entrypoing to simplify scripting

TMP: remove the comments

TMP: does hardcording the UID fix it?

TMP: not executing

TMP: how long to install dev deps

TMP: add pytset split

TMP: quiet pull the image

TMP: correct commands

diff --git a/.github/workflows/verify-docker-image.yml b/.github/workflows/verify-docker-image.yml
--- a/.github/workflows/verify-docker-image.yml
+++ b/.github/workflows/verify-docker-image.yml
@@ -6,23 +6,288 @@ on:
       - master
 
 jobs:
-  verify_docker_image:
+  build:
     runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.build.outputs.version }}
+    steps:
+      - uses: actions/checkout@v4
+      - id: build
+        uses: ./.github/actions/build-docker
+        with:
+          mode: development
+          push: true
+          username: ${{ secrets.DOCKER_USER }}
+          password: ${{ secrets.DOCKER_PASS }}
+
+  count_cores:
+    runs-on: ubuntu-latest
+    outputs:
+      count: ${{ steps.cores.outputs.count }}
+    steps:
+      - name: Count Cores
+        id: cores
+        shell: bash
+        run: |
+          echo "cores: $(nproc)"
+          echo "count=$(nproc)" >> $GITHUB_OUTPUT
+
+  check_failure:
+    runs-on: ubuntu-latest
+    needs: [build]
 
     steps:
       - uses: actions/checkout@v4
 
-      - name: Build Docker image
-        id: build
-        uses: ./.github/actions/build-docker
+      - id: failure
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          command: |
+            exit 1
+        continue-on-error: true
+      - name: Verify failure
+        if: always()
+        run: |
+          if [ "${{ steps.failure.outcome }}" -ne "failure" ]; then
+            echo "Expected failure"
+            exit 1
+          fi
+
+  check:
+    runs-on: ubuntu-latest
+    needs: [build]
+
+    steps:
+      - uses: actions/checkout@v4
 
       - name: Smoke test
         uses: ./.github/actions/run-docker
         with:
-          image: ${{ steps.build.outputs.tags }}
-          options:
-          run: |
+          version: ${{ needs.build.outputs.version }}
+          command: |
             make update_deps
             echo 'from olympia.lib.settings_base import *' > settings_local.py
             DJANGO_SETTINGS_MODULE='settings_local' python3 ./manage.py check
 
+            pip show olympia
+
+            ./scripts/check_requirements_installed.sh prod.txt
+            ./scripts/check_requirements_installed.sh pip.txt
+            ./scripts/check_requirements_installed.sh dev.txt
+
+  main:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+    strategy:
+      matrix:
+        group: [1, 2, 3, 4, 5]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Pytest (main)
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          up: true
+          command: |
+            make update_deps
+            pytest \
+              --splits 5 \
+              --group ${{ matrix.group }} \
+              -n ${{ needs.count_cores.outputs.count }} \
+              -m 'not es_tests and not needs_locales_compilation and not static_assets and not internal_routes_allowed' \
+              -v src/olympia/ \
+              --ignore src/olympia/addons/ \
+              --ignore src/olympia/devhub/ \
+              --ignore src/olympia/files/ \
+              --ignore src/olympia/reviewers/ \
+              --ignore src/olympia/ratings/ \
+              --ignore src/olympia/amo/ \
+              --ignore src/olympia/lib/ \
+              --ignore src/olympia/signing \
+              --ignore src/olympia/versions/ \
+              --ignore src/olympia/zadmin
+
+  devhub:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+    strategy:
+      matrix:
+        group: [1, 2, 3, 4, 5]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Pytest (devhub)
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          up: true
+          command: |
+            make update_deps
+            pytest \
+              --splits 5 \
+              --group ${{ matrix.group }} \
+              -n ${{ needs.count_cores.outputs.count }} \
+              -m 'not es_tests and not needs_locales_compilation and not static_assets' \
+              -v src/olympia/devhub/
+
+  es-tests:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Pytest (es-testst)
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          up: true
+          env: |
+            xpack.security.enabled=false
+            xpack.monitoring.enabled=false
+            xpack.graph.enabled=false
+            xpack.watcher.enabled=false
+            discovery.type=single-node
+            cluster.name=default-cluster
+            ES_JAVA_OPTS=-Xms256m -Xmx256m
+          command: |
+              make update_deps
+              pytest \
+                -n ${{ needs.count_cores.outputs.count }} \
+                -m "es_tests and not needs_locales_compilation and not static_assets" \
+                -v src/olympia/
+
+  addons-versions-files-ratings:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+    strategy:
+      matrix:
+        group: [1, 2, 3, 4, 5]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Pytest (addons-versions-files-ratings)
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          up: true
+          command: |
+              make update_deps
+              pytest \
+                --splits 5 \
+                --group ${{ matrix.group }} \
+                -n ${{ needs.count_cores.outputs.count }} \
+                -m 'not es_tests and not needs_locales_compilation and not static_assets' \
+                -v src/olympia/addons/ src/olympia/versions/ src/olympia/files/ src/olympia/ratings/
+
+  amo-lib-locales-and-signing:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Pytest (amo-lib-locales-and-signing)
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          up: true
+          command: |
+              make update_deps
+              pytest \
+                -n ${{ needs.count_cores.outputs.count }} \
+                -m 'needs_locales_compilation' \
+                -v src/olympia/
+
+  reviewers-and-zadmin:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Pytest (es-testst)
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          up: true
+          env: |
+            AUTOGRAPH_SERVER_URL=true
+          command: |
+              make update_deps
+              echo "ur: $AUTOGRAPH_SERVER_URL"
+              pytest \
+                -n ${{ needs.count_cores.outputs.count }} \
+                -m 'internal_routes_allowed' \
+                -v src/olympia/
+
+  codestyle:
+    runs-on: ubuntu-latest
+    needs: [build]
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Lint and codestyle
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          command: |
+            make update_deps
+            make lint-codestyle
+
+  assets:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Static Assets
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          command: |
+            make update_deps
+            make update_assets
+            pytest \
+              -n ${{ needs.count_cores.outputs.count }} \
+              -m "static_assets" -v src/olympia/
+            make run_js_tests
+
+  locales:
+    runs-on: ubuntu-latest
+    needs: [count_cores, build]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
+
+      - name: Extract Locales
+        uses: ./.github/actions/run-docker
+        with:
+          version: ${{ needs.build.outputs.version }}
+          command: |
+            make update_deps
+            make extract_locales
+
+      - name: Push Locales (dry-run)
+        if: github.event_name == 'pull_request'
+        shell: bash
+        run: |
+          if [[ ${{ github.event.pull_request.head.repo.fork}} == 'true' ]]; then
+            echo """
+            Github actions are not authorized to push from workflows triggered by forks.
+            We cannot verify if the l10n extraction push will work or not.
+            Please submit a PR from the base repository if you are modifying l10n extraction scripts.
+            """
+
+            exit 0
+          fi
+
+          make push_locales ARGS="--dry-run"
